FROM jakelee8/steam:onbuild
MAINTAINER Jake Lee <jake@jakelee.net>
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
